In [1]:
import pandas as pd

df=pd.read_csv('jointure.csv')

In [5]:
df=df[['title', 'nbre_entrees', 
       'distributeur', 'country', 'genre', 'date', 'public', 'durée',
        'directeur', 'acteurs', 'note_presse',
       'box_office_france', 'prix', 'nominations', 'budget_def']]

In [6]:
df.columns

Index(['title', 'nbre_entrees', 'distributeur', 'country', 'genre', 'date',
       'public', 'durée', 'directeur', 'acteurs', 'note_presse',
       'box_office_france', 'prix', 'nominations', 'budget_def'],
      dtype='object')

In [32]:
import pyodbc
import os

server='projet-affluence-cinema-mlrecap.database.windows.net'
database='BDD_boxoffice'
username = 'project_affluence_cinema'
password = os.getenv('password')
driver = 'ODBC Driver 18 for SQL Server'
print(password)


conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()



cursor.execute("DROP TABLE IF EXISTS scrapings")
cursor.execute(""" 
       CREATE TABLE scrapings(
            id INT PRIMARY KEY IDENTITY(1,1),
            titre VARCHAR(255) NOT NULL,
            nbre_entrees INTEGER NOT NULL,
            country VARCHAR(255) NOT NULL,
            genre VARCHAR(255) NOT NULL,
            date DATE NOT NULL,
            publico VARCHAR(255) NOT NULL,
            durée INTEGER NOT NULL,
            directeur VARCHAR(255) NOT NULL,
            acteurs VARCHAR(255) NOT NULL,
            note_presse FLOAT NOT NULL,
            box_office_FR INTEGER NOT NULL,
            prix INTEGER NOT NULL,
            nominations INTEGER NOT NULL,
            budget_def FLOAT NOT NULL,
            )
            """)

# Valider la transaction
conn.commit()

# Fermer le curseur et la connexion
cursor.close()
conn.close()

*Boxoffice1

In [24]:
def ajouter_valeures(titre,nbre_entrees, country, genre,date, publico, durée,directeur,acteurs,note_presse,box_office_FR,prix,nominations,budget_def) -> int: 
    conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'
    conn = pyodbc.connect(conn_str)
    


# Créer un curseur
    cursor = conn.cursor()
    cursor.execute(""" 
        INSERT INTO scrapings
        VALUES ( ?,?, ?, ?, ?,?,?, ?, ?, ?,?,?,?,?)           
        """, ( titre,nbre_entrees, country, genre,date, publico, durée,directeur,acteurs,note_presse,box_office_FR,prix,nominations,budget_def))       
  
    conn.commit()
    conn.close()

In [17]:
import re
from datetime import datetime

def convert_duration(duration_str):
    # Utilisation d'une expression régulière pour extraire les heures et les minutes
    match = re.match(r'(\d+)h(\d+)', duration_str)
    if match:
        hours = int(match.group(1))
        minutes = int(match.group(2))
        total_minutes = hours * 60 + minutes
        return total_minutes
    else:
        return None
    
def convert_date(date_str):
    # Convertir la chaîne de date en objet datetime
    date_obj = datetime.strptime(date_str, '%d/%m/%Y')
    # Formater la date au format YYYY-MM-DD
    formatted_date = date_obj.strftime('%Y-%m-%d')
    return formatted_date

In [14]:
df.columns

Index(['title', 'nbre_entrees', 'distributeur', 'country', 'genre', 'date',
       'public', 'durée', 'directeur', 'acteurs', 'note_presse',
       'box_office_france', 'prix', 'nominations', 'budget_def'],
      dtype='object')

In [16]:
df['date'].head(10)

0    30/01/2008
1    31/10/2008
2    21/05/2008
3    13/08/2008
4    09/07/2008
5    29/10/2008
6    06/02/2008
7    30/04/2008
8    18/06/2008
9    23/07/2008
Name: date, dtype: object

In [43]:
df = df[df['date'] != '00/00/0000']

In [47]:
for row,value in df.iterrows():
    print(row)
    titre=value['title']
    nbre_entrees=value['nbre_entrees']
    print(nbre_entrees)
    NBRE = nbre_entrees.replace(' ', '')
    print(NBRE)
    nbre2=int(NBRE)
    country=value['country']
    genre=value['genre']
    date=convert_date(value['date'])
    publico=value['public']
    durée=convert_duration(value['durée'])
    directeur=value['directeur']
    acteurs=value['acteurs']
    note_presse=value['note_presse']
    note_presse_str = note_presse.replace(',', '.')
    note_presse_float = float(note_presse_str)
    box_office_FR=int(value['box_office_france'])
    prix=str(value['prix'])
    prix = prix.replace('#', '')
    print('ici prix', prix)
    if prix is None or prix == '':
        prix = 1
    # prix=int(value['prix'])
    nominations=int(value['nominations'])
    budget_def=str(value['budget_def'])
    budget_def_str = budget_def.replace(' ', '')
    budget_defi = float(budget_def_str)
    
    ajouter_valeures(titre,nbre2, country, genre,date, publico, durée,directeur,acteurs,note_presse_float,box_office_FR,prix,nominations,budget_defi)

0
3 007 811
3007811
ici prix 5
1
1 703 897
1703897
ici prix 0
2
1 674 041
1674041
ici prix 1
3
1 271 688
1271688
ici prix 6
4
955 571
955571
ici prix 9
5
408 413
408413
ici prix 0
6
391 630
391630
ici prix 0
7
866 316
866316
ici prix 0
8
61 860
61860
ici prix 0
9
517 088
517088
ici prix 0
10
1 265 163
1265163
ici prix 0
11
474 853
474853
ici prix 0
12
409 884
409884
ici prix 1
13
826 315
826315
ici prix 6
14
804 345
804345
ici prix 1
15
1 573 648
1573648
ici prix 21
16
2 010 736
2010736
ici prix 1
17
657 191
657191
ici prix 6
18
802 975
802975
ici prix 3
19
135 858
135858
ici prix 12
20
341 820
341820
ici prix 1
21
523 901
523901
ici prix 0
22
383 904
383904
ici prix 0
23
361 394
361394
ici prix 0
24
462 343
462343
ici prix 0
25
327 920
327920
ici prix 0
26
323 499
323499
ici prix 0
27
378 651
378651
ici prix 0
28
420 262
420262
ici prix 1
29
321 940
321940
ici prix 0
30
262 793
262793
ici prix 0
31
237 466
237466
ici prix 0
32
157 484
157484
ici prix 0
33
182 247
182247
ici prix 0
34
114 688
114688
ici prix 0
35
321 480
321480
ici prix 0
36
135 779
135779
ici prix 3
37
163 878
163878
ici prix 0
38
136 000
136000
ici prix 0
39
130 295
130295
ici prix
40
90 015
90015
ici prix 2
41
129 674
129674
ici prix 0
42
135 889
135889
ici prix 0
43
101 785
101785
ici prix 11
44
86 135
86135
ici prix 0
45
100 375
100375
ici prix 0
46
61 454
61454
ici prix 0
47
55 407
55407
ici prix 0
48
67 614
67614
ici prix 0
49
52 804
52804
ici prix 2
50
56 342
56342
ici prix 0
51
58 241
58241
ici prix 0
52
53 396
53396
ici prix 0
53
29 486
29486
ici prix 0
54
31 206
31206
ici prix 0
55
1 751 471
1751471
ici prix 0
56
193 755
193755
ici prix 0
57
12 386
12386
ici prix 0
58
289 036
289036
ici prix 12
59
1 011 566
1011566
ici prix 0
60
31 177
31177
ici prix 1
61
2 486 291
2486291
ici prix 2
62
101 302
101302
ici prix 0
63
956 475
956475
ici prix 1
64
60 246
60246
ici prix 4
65
53 122
53122
ici prix 0
66
15 238
15238
ici prix 1
67
1 951 074
1951074
ici prix 17
68
9 104
9104
ici prix 0
69
169 740
169740
ici prix 2
70
36 264
36264
ici prix 0
71
24 526
24526
ici prix 0
72
584 326
584326
ici prix 5
73
90 547
90547
ici prix 0
74
458 730
458730
ici prix 3
75
150 199
150199
ici prix 0
76
166 035
166035
ici prix 0
77
162 862
162862
ici prix 0
78
517 322
517322
ici prix 5
79
47 594
47594
ici prix 0
80
201 177
201177
ici prix 3
81
33 297
33297
ici prix 0
82
444 083
444083
ici prix 1
83
318 681
318681
ici prix 0
84
117 110
117110
ici prix 1
85
254 575
254575
ici prix 2
86
260 479
260479
ici prix 4
87
130 527
130527
ici prix 0
88
266 966
266966
ici prix 0
89
264 579
264579
ici prix 0
90
189 810
189810
ici prix 0
91
265 553
265553
ici prix 0
92
399 704
399704
ici prix 0
93
1 096 518
1096518
ici prix 3
94
196 577
196577
ici prix 0
95
485 455
485455
ici prix 1
96
826 848
826848
ici prix 0
97
375 509
375509
ici prix 0
98
280 835
280835
ici prix 0
99
162 306
162306
ici prix 0
100
27 883
27883
ici prix 0
101
22 729
22729
ici prix 1
102
76 338
76338
ici prix 0
103
69 804
69804
ici prix 0
104
242 603
242603
ici prix 0
105
49 817
49817
ici prix 0
106
114 801
114801
ici prix 0
107
309 843
309843
ici prix 1
108
185 958
185958
ici prix 0
109
134 071
134071
ici prix 0
110
112 959
112959
ici prix 0
111
85 678
85678
ici prix 0
112
24 823
24823
ici prix 0
113
151 229
151229
ici prix 6
114
68 461
68461
ici prix 0
115
148 178
148178
ici prix 0
116
507 434
507434
ici prix 6
117
185 758
185758
ici prix 0
118
2 171 810
2171810
ici prix 1
119
1 707 373
1707373
ici prix 1
120
834 805
834805
ici prix 6
121
858 599
858599
ici prix 14
122
1 548 582
1548582
ici prix 1
123
792 503
792503
ici prix 0
124
340 937
340937
ici prix 13
125
694 177
694177
ici prix 0
126
650 335
650335
ici prix 2
127
527 454
527454
ici prix 3
128
438 793
438793
ici prix 8
129
601 163
601163
ici prix 3
130
996 860
996860
ici prix 0
131
366 392
366392
ici prix 0
132
616 912
616912
ici prix 11
133
730 466
730466
ici prix 0
134
320 230
320230
ici prix 0
135
375 210
375210
ici prix 3
136
640 412
640412
ici prix 5
137
415 679
415679
ici prix 3
138
491 328
491328
ici prix 0
139
419 722
419722
ici prix 2
140
374 153
374153
ici prix 5
141
294 524
294524
ici prix 0
142
403 555
403555
ici prix 2
143
670 642
670642
ici prix 0
144
275 370
275370
ici prix 0
145
230 325
230325
ici prix 0
146
399 396
399396
ici prix 1
147
308 469
308469
ici prix 13
148
305 743
305743
ici prix 2
149
207 069
207069
ici prix 7
150
338 027
338027
ici prix 5
151
497 240
497240
ici prix 1
152
405 218
405218
ici prix 0
153
401 269
401269
ici prix 0
154
331 714
331714
ici prix 0
155
427 400
427400
ici prix 2
156
173 666
173666
ici prix 0
157
398 998
398998
ici prix 0
158
407 863
407863
ici prix 0
159
261 617
261617
ici prix 0
160
200 643
200643
ici prix 8
161
302 104
302104
ici prix 1
162
250 854
250854
ici prix 0
163
160 628
160628
ici prix 2
164
250 169
250169
ici prix 0
165
293 727
293727
ici prix 4
166
272 149
272149
ici prix 2
167
160 674
160674
ici prix 0
168
234 693
234693
ici prix 0
169
212 679
212679
ici prix 0
170
153 606
153606
ici prix 0
171
177 058
177058
ici prix 13
172
105 232
105232
ici prix 0
173
231 815
231815
ici prix 1
174
156 849
156849
ici prix 0
175
67 968
67968
ici prix 0
176
142 476
142476
ici prix 0
177
208 706
208706
ici prix 0
178
216 132
216132
ici prix 0
179
155 745
155745
ici prix 1
180
216 381
216381
ici prix 11
181
92 000
92000
ici prix 8
182
113 754
113754
ici prix 0
183
181 888
181888
ici prix 0
184
125 972
125972
ici prix 1
185
173 072
173072
ici prix 0
186
166 144
166144
ici prix 0
187
84 236
84236
ici prix 0
188
152 431
152431
ici prix 0
189
104 625
104625
ici prix 0
190
125 609
125609
ici prix 0
191
106 182
106182
ici prix 0
192
97 914
97914
ici prix 3
193
133 365
133365
ici prix 1
194
127 061
127061
ici prix 0
195
122 611
122611
ici prix 0
196
84 542
84542
ici prix 0
197
79 041
79041
ici prix 0
198
53 466
53466
ici prix 0
199
108 757
108757
ici prix
200
116 038
116038
ici prix 0
201
93 357
93357
ici prix 0
202
82 448
82448
ici prix 1
203
84 934
84934
ici prix 3
204
115 483
115483
ici prix 0
205
70 911
70911
ici prix 1
206
59 797
59797
ici prix 0
207
54 263
54263
ici prix 1
208
48 535
48535
ici prix 1
209
70 380
70380
ici prix 0
210
48 171
48171
ici prix 1
211
71 287
71287
ici prix 0
212
67 323
67323
ici prix 0
213
55 491
55491
ici prix 1
214
77 647
77647
ici prix 0
215
66 767
66767
ici prix 0
216
32 293
32293
ici prix 1
217
33 737
33737
ici prix 0
218
55 466
55466
ici prix 0
219
52 189
52189
ici prix 0
220
55 077
55077
ici prix 0
221
44 431
44431
ici prix 0
222
49 993
49993
ici prix 0
223
49 104
49104
ici prix 0
224
31 899
31899
ici prix 1
225
40 640
40640
ici prix 0
226
33 563
33563
ici prix 0
227
165 113
165113
ici prix 2
228
22 746
22746
ici prix 6
230
3 088 796
3088796
ici prix 4
231
766 547
766547
ici prix 1
232
1 700 096
1700096
ici prix 1
233
874 013
874013
ici prix 0
234
662 329
662329
ici prix 1
235
1 116 637
1116637
ici prix 9
236
624 517
624517
ici prix 0
237
952 331
952331
ici prix 3
238
606 009
606009
ici prix 0
239
630 433
630433
ici prix 0
240
452 777
452777
ici prix 4
241
482 752
482752
ici prix 0
242
506 944
506944
ici prix 0
243
506 716
506716
ici prix 2
244
345 633
345633
ici prix 0
245
379 298
379298
ici prix 0
246
277 516
277516
ici prix 20
247
622 019
622019
ici prix 0
248
430 479
430479
ici prix 4
249
555 362
555362
ici prix 0
250
294 261
294261
ici prix 0
251
425 873
425873
ici prix 0
252
240 021
240021
ici prix 0
253
322 469
322469
ici prix 0
254
210 915
210915
ici prix 0
255
346 788
346788
ici prix 1
256
327 730
327730
ici prix 1
257
280 435
280435
ici prix 0
258
277 394
277394
ici prix 1
259
310 690
310690
ici prix 0
260
350 054
350054
ici prix 0
261
429 165
429165
ici prix 0
262
251 849
251849
ici prix 0
263
317 867
317867
ici prix 0
264
282 270
282270
ici prix 0
265
241 732
241732
ici prix 3
266
272 047
272047
ici prix 2
267
183 302
183302
ici prix 0
268
167 705
167705
ici prix 1
269
191 616
191616
ici prix 0
270
235 194
235194
ici prix 0
271
156 464
156464
ici prix 6
272
110 345
110345
ici prix 7
273
242 068
242068
ici prix 0
274
241 007
241007
ici prix 0
275
205 065
205065
ici prix 1
276
154 731
154731
ici prix 0
277
155 625
155625
ici prix 0
278
179 700
179700
ici prix 0
279
134 383
134383
ici prix 1
280
137 403
137403
ici prix 0
281
140 644
140644
ici prix 1
282
147 141
147141
ici prix 0
283
176 199
176199
ici prix 0
284
154 354
154354
ici prix 0
285
194 391
194391
ici prix 0
286
196 506
196506
ici prix 1
287
99 266
99266
ici prix 2
288
189 085
189085
ici prix 0
289
167 074
167074
ici prix 1
290
105 888
105888
ici prix 0
291
126 403
126403
ici prix 7
292
170 359
170359
ici prix 0
293
118 305
118305
ici prix 0
294
83 785
83785
ici prix 0
295
114 289
114289
ici prix 0
296
101 633
101633
ici prix 0
297
81 541
81541
ici prix 0
298
61 255
61255
ici prix 0
299
78 428
78428
ici prix 0
300
31 752
31752
ici prix 0
301
30 175
30175
ici prix 3
302
26 330
26330
ici prix 2
303
49 603
49603
ici prix 0
304
23 831
23831
ici prix 0

OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

In [ ]:
import pyodbc
import os

server='projet-affluence-cinema-mlrecap.database.windows.net'
database='BDD_boxoffice'
username = 'project_affluence_cinema'
password = os.getenv('password')
driver = 'ODBC Driver 18 for SQL Server'
print(password)


conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()



cursor.execute("DROP TABLE IF EXISTS scrapings")
cursor.execute(""" 
       CREATE TABLE scrapings(
            id INT PRIMARY KEY IDENTITY(1,1),
            title VARCHAR(255) NOT NULL,
            distributeur VARCHAR(255) NOT NULL,
            genre VARCHAR(255) NOT NULL,
            dati VARCHAR(255) NOT NULL)
            """)

# Valider la transaction
conn.commit()

# Fermer le curseur et la connexion
cursor.close()
conn.close()



def ajouter_valeures(title, distributeur, genre,dati) -> int: 
    conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'
    conn = pyodbc.connect(conn_str)
    


# Créer un curseur
    cursor = conn.cursor()
    cursor.execute(""" 
        INSERT INTO scrapings
        VALUES ( ?, ?, ?, ?)           
        """, ( title, distributeur, genre,dati))       
  
    conn.commit()
    conn.close()